language: java

jdk: openjdk13

after_success :
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      kirbel74@gmail.com
    on_success: never
    on_failure: always

env:
  global: CODECOV_TOKEN="2eedcc6d-9189-4ae0-bf90-cd5d79e1e048"